---
title: "Readme"
author: "Constantinos Lirigos"
date: "22December 2016"
output: html_document
---
This is peer-graded assignment for the coursera Getting and Cleaning Data.
The script required by the assignment , called "run_analysis.R" does the following:

##1) Merges the training and the test sets to create one data set.
####test set:
-"X_test.txt": 2947 obs, 561 variables (from "features.txt")
-"subject_test.txt": 2947 obs, 1 variable (subjects)
-"y_test.txt": 2947 obs, 1 variable (activity labels)


####train set:
"X_train.txt": 7352 obs, 561 variables (from "features.txt")

"subject_train.txt":7352 obs, 1 variable (subjects)

"y_train.txt": 7352 obs, 1 variable (activity labels)


1.a) merge 3 files in test set to one = "test" and 3 files in train set to one = "train" (with cbind)
1st collumn: subject
2nd collumn: activity
3rd...563 collumns: 561 features
1.b) merge "test" & "train" to one = "data" (with rbind)
convert first 2 collumns to factors
Now we have one file ("data") with all observations (10299 = 7352 + 2947) 


2) Extracts only the measurements on the mean and standard deviation for each measurement.
2.a) create a vector (= features1 ) containing only mean & sd features. There are 86 such variables.
2.b) choose from "data" the  first two collumns plus all collumns matching the previous vector (features1$V1) and pass them to a new data frame : "data1"
data1 <- cbind(data[,1:2], select(data, one_of(features1$V1)))
The new dataframe has 88 collumns/variables ( = 2 + 86 ) and 10299 rows/observations.


3) Uses descriptive activity names to name the activities in the data set
"Activity" is a factor with 6 levels 1:6. We rename the labels taking the new names from the file 
"ativity_labels.txt"
data1$Activity <- factor(data1$Activity, levels = c(1:6), labels = Activity$V2)


4) Appropriately labels the data set with descriptive variable names.
Rename variables (collunns):
col. 1 + 2 : "Subjects", "Activity"
col. 3 up to 88: names(data1)[3:88] <- features1$V2
Now the file "data1"


5) From the data set in step 4, creates a second, independent tidy data set with the average of each variable for each activity and each subject.
Use the "reshape2" package. Melt "data1" and dcast it again having calcuated the means. 
tidy_data <- dcast(melt(data1), Subjects + Activity ~ variable, mean)
then write the file to txt file: "tidy_data.txt"
write.table(tidy_data, file = "tidy_data.txt")



